Update build-JDCLOUD-RE-CP-02-1.yml

diff --git a/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml b/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
--- a/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
+++ b/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
@@ -47,16 +47,21 @@ jobs:
         KERNEL: 4.4
       run: |
         cd /opt/padavan/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
         cp -f configs/templates/$TNAME.config .config
+        sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
-- name: Upload bin directory
+    - name: Upload bin directory
       uses: actions/upload-artifact@main
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
       with:
         name: JDX${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
         path: /opt/images/
- - name: Generate release tag
+    - name: Generate release tag
       id: tag
       if: env.UPLOAD_RELEASE == 'true' && !cancelled()
       run: |
