Update build-JDCLOUD-RE-CP-02-1.yml

diff --git a/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml b/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
--- a/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
+++ b/.github/workflows/build-JDCLOUD-RE-CP-02-1.yml
@@ -52,10 +52,10 @@ jobs:
         KERNEL: 4.4
       run: |
         cd /opt/padavan/trunk
-        if [ ! -f configs/templates/$TNAME.config ] ; then
-        echo "configs/templates/$TNAME.config not found "
-        exit 1
-        fi
+        #if [ ! -f configs/templates/$TNAME.config ] ; then
+        #echo "configs/templates/$TNAME.config not found "
+        #exit 1
+        #fi
         cp -f configs/templates/$TNAME.config .config
         sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
         ################################################################################################
@@ -125,13 +125,6 @@ jobs:
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
-        
-    - name: Upload bin directory
-      uses: actions/upload-artifact@main
-      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
-      with:
-        name: JDX${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: /opt/images/
     - name: Generate release tag
       id: tag
       if: env.UPLOAD_RELEASE == 'true' && !cancelled()
@@ -149,7 +142,7 @@ jobs:
       with:
         tag_name: ${{ steps.tag.outputs.release_tag }}
         body_path: release.txt
-        files: ${{ env.FIRMWARE }}/*
+        files: ${{ env.FIRMWARE }}/opt/images/*.trx
 
     - name: Delete workflow runs
       uses: Mattraks/delete-workflow-runs@main
