Add files via upload

diff --git a/.github/workflows/build-JDCLOUD-RE-SP-01B.yml b/.github/workflows/build-JDCLOUD-RE-SP-01B.yml
--- a/.github/workflows/build-JDCLOUD-RE-SP-01B.yml
+++ b/.github/workflows/build-JDCLOUD-RE-SP-01B.yml
@@ -1,5 +1,5 @@
 #修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
-name: Build Padavan
+name: Build JDCLOUD-RE-SP-01B
 
 on: 
   release:
@@ -48,6 +48,11 @@ jobs:
         KERNEL: 4.4
       run: |
         cd /opt/padavan/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
